# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
    LogPath             = "/tmp/log/gf-app/server"                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
    LogStdout           = true               # 日志是否输出到终端。默认为true
    ErrorStack          = true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    ErrorLogEnabled     = true               # 是否记录异常日志信息到日志中。默认为true
    ErrorLogPattern     = "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    AccessLogEnabled    = true               # 是否记录访问日志。默认为false
    AccessLogPattern    = "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
    DumpRouterMap       = false              # 是否在Server启动时打印所有的路由列表。默认为true

# Logger.
[logger]
    Path        = "/tmp/log/gf-app/log"
    Level       = "all"
    Stdout      = true
    [logger.sqlogger]
        path   = "/tmp/log/gf-app/sql"
        level  = "all"
        stdout = true


# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    type = "mysql"
    user = "goframe"
    pwd = "plingply95"
    host = "119.29.133.60"
    port = 3306
    tablename = "goframe"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true


[redis]
    default = "119.29.133.60:6379,0,plingply95?idleTimeout=600"
    cache   = "119.29.133.60:6379,goweb,plingply95?idleTimeout=600"

#OSS
[OSS]
    endpoint = "https://oss-cn-beijing.aliyuncs.com"
    fileEndpoint = "https://xinxin950618.oss-cn-beijing.aliyuncs.com"
    accessKeyId = "LTAITTDGsu8PM4kG"
    accessKeySecret = "Yo7ZGScBuHv5Gib3rVUF1SRXRuXAh4"
    bucketName = "xinxin950618"

#WECHAT
[wechat]
    token = "PLINGPLYCHANGMMYEARMONTHS"
    appid = "wx5c96b11e8a53a173"
    appsecret = "0d9b94eebf4eafcbfb180dda71e0b868"