# HTTP Server配置
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	ServerAgent    = "gf-demos"
	LogPath        = "/www/wwwroot/golang/src/log/goframe/server"
	NameToUriType  = 2
	RouteOverWrite = true

# 全局日志配置
[logger]
    Path   = "/www/wwwroot/golang/src/log/goframe/glob"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# 数据库连接
[database]
    link  = "mysql:goframe:plingply95@tcp(127.0.0.1:3306)/goframe"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/gf-demos/sql"
        Level  = "all"
        Stdout = true

# swagger api页面查看账号密码
[swagger]
    user        = "root"
    pass        = "111111"
    schemes     = ["http"]
    version     = "1.0"
    title       = "示例服务API"
    description = """
`GoFrame`基础开发框架示例服务API接口文档。
    """